# Generator Format:
# Anything in '<>' is required
# Anything in '[]' is optional
# Example:
# <player name>:
#   [kills]: ...
#
# Actual Generator Format:
# <world name>:
#   <item to spawn>:
#     - pos:
#         x: <x coord>
#         y: <y coord>
#         z: <z coord>
#       count: [the amount to spawn]

world:
  coal:
    - pos:
        x: 10
        y: 10
        z: 10
      speed: 5
